### ISSUE TITLE
NPE when program is starting

### ISSUE THREAD

**Issue by rrybalkin** [rrybalkin/vouchers#10]
2017-03-01 09:02:36,534 [ERROR][read][gui.controller.impl.MainWindowController] - Ошибка при загрузке Tabs: 
java.lang.NullPointerException
	at com.romansun.gui.controller.impl.FirstTabController.loadVisitors(Unknown Source)
	at com.romansun.gui.controller.impl.FirstTabController.initialize(Unknown Source)
	at javafx.fxml.FXMLLoader.load(Unknown Source)
	at javafx.fxml.FXMLLoader.load(Unknown Source)
	at com.romansun.gui.controller.impl.MainWindowController.loadTab(Unknown Source)
	at com.romansun.gui.controller.impl.MainWindowController.initialize(Unknown Source)
	at javafx.fxml.FXMLLoader.load(Unknown Source)
	at javafx.fxml.FXMLLoader.load(Unknown Source)
	at javafx.fxml.FXMLLoader.load(Unknown Source)
	at javafx.fxml.FXMLLoader.load(Unknown Source)
	at javafx.fxml.FXMLLoader.load(Unknown Source)
	at javafx.fxml.FXMLLoader.load(Unknown Source)
	at javafx.fxml.FXMLLoader.load(Unknown Source)
	at com.romansun.gui.viewbuilder.WindowBuilder.start(Unknown Source)
	at com.sun.javafx.application.LauncherImpl$5.run(Unknown Source)
	at com.sun.javafx.application.PlatformImpl$5.run(Unknown Source)
	at com.sun.javafx.application.PlatformImpl$4$1.run(Unknown Source)
	at com.sun.javafx.application.PlatformImpl$4$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl$4.run(Unknown Source)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.access$100(Unknown Source)
	at com.sun.glass.ui.win.WinApplication$3$1.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by rrybalkin** [comment]
Fixed
