### ISSUE TITLE
TLS connection problem

### ISSUE THREAD

**Issue by rrybalkin** [rrybalkin/vouchers#11]
2017-03-01 09:44:36,457 [ERROR][read][gui.controller.impl.FirstTabController] - Ошибка при загрузке фильтров и групп: 
org.hibernate.exception.GenericJDBCException: Could not open connection
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:54)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:110)
	at org.hibernate.engine.jdbc.internal.LogicalConnectionImpl.obtainConnection(LogicalConnectionImpl.java:304)
	at org.hibernate.engine.jdbc.internal.LogicalConnectionImpl.getConnection(LogicalConnectionImpl.java:169)
	at org.hibernate.engine.jdbc.internal.proxy.ConnectionProxyHandler.extractPhysicalConnection(ConnectionProxyHandler.java:82)
	at org.hibernate.engine.jdbc.internal.proxy.ConnectionProxyHandler.continueInvocation(ConnectionProxyHandler.java:138)
	at org.hibernate.engine.jdbc.internal.proxy.AbstractProxyHandler.invoke(AbstractProxyHandler.java:81)
	at $Proxy20.prepareStatement(Unknown Source)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:147)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:166)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:145)
	at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:1854)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1831)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1811)
	at org.hibernate.loader.Loader.doQuery(Loader.java:899)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:341)
	at org.hibernate.loader.Loader.doList(Loader.java:2516)
	at org.hibernate.loader.Loader.doList(Loader.java:2502)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2332)
	at org.hibernate.loader.Loader.list(Loader.java:2327)
	at org.hibernate.loader.criteria.CriteriaLoader.list(CriteriaLoader.java:124)
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1621)
	at org.hibernate.internal.CriteriaImpl.list(CriteriaImpl.java:374)
	at com.romansun.hibernate.DAO.impl.AssociationDAOImpl.getAllAssociations(Unknown Source)
	at com.romansun.gui.controller.impl.FirstTabController.loadFilters(Unknown Source)
	at com.romansun.gui.controller.impl.FirstTabController.initialize(Unknown Source)
	at javafx.fxml.FXMLLoader.load(Unknown Source)
	at javafx.fxml.FXMLLoader.load(Unknown Source)
	at com.romansun.gui.controller.impl.MainWindowController.loadTab(Unknown Source)
	at com.romansun.gui.controller.impl.MainWindowController.initialize(Unknown Source)
	at javafx.fxml.FXMLLoader.load(Unknown Source)
	at javafx.fxml.FXMLLoader.load(Unknown Source)
	at javafx.fxml.FXMLLoader.load(Unknown Source)
	at javafx.fxml.FXMLLoader.load(Unknown Source)
	at javafx.fxml.FXMLLoader.load(Unknown Source)
	at javafx.fxml.FXMLLoader.load(Unknown Source)
	at javafx.fxml.FXMLLoader.load(Unknown Source)
	at com.romansun.gui.viewbuilder.WindowBuilder.start(Unknown Source)
	at com.sun.javafx.application.LauncherImpl$5.run(Unknown Source)
	at com.sun.javafx.application.PlatformImpl$5.run(Unknown Source)
	at com.sun.javafx.application.PlatformImpl$4$1.run(Unknown Source)
	at com.sun.javafx.application.PlatformImpl$4$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl$4.run(Unknown Source)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.access$100(Unknown Source)
	at com.sun.glass.ui.win.WinApplication$3$1.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.sql.SQLException: Listener refused the connection with the following error:
ORA-12528, TNS:listener: all appropriate instances are blocking new connections
 
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:458)
	at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:546)
	at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:236)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:32)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:521)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.hibernate.service.jdbc.connections.internal.DriverManagerConnectionProviderImpl.getConnection(DriverManagerConnectionProviderImpl.java:193)
	at org.hibernate.internal.AbstractSessionImpl$NonContextualJdbcConnectionAccess.obtainConnection(AbstractSessionImpl.java:292)
	at org.hibernate.engine.jdbc.internal.LogicalConnectionImpl.obtainConnection(LogicalConnectionImpl.java:297)
	... 45 more
Caused by: oracle.net.ns.NetException: Listener refused the connection with the following error:
ORA-12528, TNS:listener: all appropriate instances are blocking new connections
 
	at oracle.net.ns.NSProtocol.connect(NSProtocol.java:395)
	at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1102)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:320)
	... 54 more
2017-03-01 09:44:36,461 [ERROR][read][gui.controller.impl.MainWindowController] - Ошибка при загрузке Tabs: 
java.lang.NullPointerException
	at com.romansun.gui.controller.impl.FirstTabController.loadVisitors(Unknown Source)
	at com.romansun.gui.controller.impl.FirstTabController.initialize(Unknown Source)
	at javafx.fxml.FXMLLoader.load(Unknown Source)
	at javafx.fxml.FXMLLoader.load(Unknown Source)
	at com.romansun.gui.controller.impl.MainWindowController.loadTab(Unknown Source)
	at com.romansun.gui.controller.impl.MainWindowController.initialize(Unknown Source)
	at javafx.fxml.FXMLLoader.load(Unknown Source)
	at javafx.fxml.FXMLLoader.load(Unknown Source)
	at javafx.fxml.FXMLLoader.load(Unknown Source)
	at javafx.fxml.FXMLLoader.load(Unknown Source)
	at javafx.fxml.FXMLLoader.load(Unknown Source)
	at javafx.fxml.FXMLLoader.load(Unknown Source)
	at javafx.fxml.FXMLLoader.load(Unknown Source)
	at com.romansun.gui.viewbuilder.WindowBuilder.start(Unknown Source)
	at com.sun.javafx.application.LauncherImpl$5.run(Unknown Source)
	at com.sun.javafx.application.PlatformImpl$5.run(Unknown Source)
	at com.sun.javafx.application.PlatformImpl$4$1.run(Unknown Source)
	at com.sun.javafx.application.PlatformImpl$4$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl$4.run(Unknown Source)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.access$100(Unknown Source)
	at com.sun.glass.ui.win.WinApplication$3$1.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
2017-03-01 09:44:55,979 [INFO ][main][base.StartWindow] - Start program ...
[applog.zip](https://github.com/rrybalkin/project-vouchers/files/924413/applog.zip)

**Comment by rrybalkin** [comment]
Fixed
